name: Lint check

on:
  pull_request:
    branches: [ master ]
jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: echo
        run: |
          echo runing make lint-components
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"
      - name: lint
        run: make lint-components