name: Build and deploy prometheus alert migrator image to dockerhub
on:
  release:
    types: [published]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push Docker images
        run: |
          IMAGE_TAG=${{ github.event.release.tag_name }} make docker-buildx
          IMAGE_TAG=latest make docker-buildx
