name: Build and deploy prometheus alert migrator image to dockerhub
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build images release
        run: IMAGE_TAG=${{ github.event.release.tag_name }} make docker-build
      - name: Push images release
        run: IMAGE_TAG=${{ github.event.release.tag_name }} make docker-push
      - name: Build images latest
        run: IMAGE_TAG=latest make docker-build
      - name: Push images latest
        run: IMAGE_TAG=latest make docker-push